version: '3'
name: beets-cli

services:
  beets:
    image: yacoob/beets
    container_name: beets-cli
    hostname: beets
    volumes:
      - /volume1/sw/beets:/home/yacoob/.config/beets
      - /volume1/music:/music
      - $PWD:/input
    restart: no
    stdin_open: true
    tty: true
