name: beets-cli
services:
  beets:
    image: ghcr.io/yacoob/beets
    container_name: beets-cli
    hostname: beets
    volumes:
      - /srv/sw/beets:/home/yacoob/.config/beets
      - /srv/music:/music
      - $PWD:/input
    restart: no
    stdin_open: true
    tty: true
