library: /music/beetsdb
directory: /music
plugins:
#  - autobpm
  - describe
  - duplicates
  - embedart
  - fetchart
  - info
  - inline
  - lastgenre
  - mbsync
  - musicbrainz
  - missing
  - permissions
  - replaygain
  - scrub
  - thumbnails

original_date: yes
per_disc_numbering: yes

import:
  move: yes
  write: yes
  resume: yes
  from_scratch: yes
  languages: en

permissions:
  file: 664
  dir: 755

paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,$disc-}$track $title
    comp: Compilations/$album%aunique{}/%if{$multidisc,$disc-}$track $title

item_fields:
  multidisc: 1 if disctotal > 1 else 0

match:
  strong_rec_thresh: 0.1
  preferred:
    countries: [US, GB|UK]
    media: [CD, Digital Media|File]
    original_year: yes

# plugin config
#
fetchart:
  cautious: yes
  cover_names: front covert art

lastgenre:
  prefer_specific: yes
  canonical: yes

replaygain:
  backend: ffmpeg
  auto: yes
