name: Build and push image to GitHub Container Registry

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yacoob/beets
  SHOULD_PUSH: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_call' }}

jobs:
  build:
    name: Build and optionally push the image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Set image names
        run: |
          echo "TARGET=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Work out container tags
        uses: docker/metadata-action@v5
        id: docker-meta
        with:
          images: ${{ env.TARGET }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up docker builder (buildx)
        uses: docker/setup-buildx-action@v3

      - name: Build and optionally push the docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          target: beets
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          tags: ${{ steps.docker-meta.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.TARGET }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: ${{ env.SHOULD_PUSH == 'true' }}
